import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import type { Project, RoomRender } from "../types/supabase";

function safeFileName(title: string) {
  const normalized = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized || "project";
}

function addFooter(pdf: jsPDF) {
  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setFontSize(10);
  pdf.setTextColor(120, 120, 120);
  pdf.text("Generated by Kairos", 14, pageHeight - 10);
}

async function elementToPngDataUrl(element: HTMLElement) {
  const canvas = await html2canvas(element, {
    backgroundColor: "#111111",
    scale: 2,
    useCORS: true,
  });
  return canvas.toDataURL("image/png");
}

async function captureFloorPlan(project: Project): Promise<string | null> {
  if (!project.floor_plan_url) {
    return null;
  }

  return captureRenderImage(project.floor_plan_url);
}

async function captureRenderImage(imageUrl: string): Promise<string | null> {
  const wrapper = document.createElement("div");
  wrapper.style.position = "fixed";
  wrapper.style.left = "-10000px";
  wrapper.style.top = "0";
  wrapper.style.width = "1000px";
  wrapper.style.background = "#111111";

  const img = document.createElement("img");
  img.src = imageUrl;
  img.crossOrigin = "anonymous";
  img.style.width = "100%";
  img.style.display = "block";
  wrapper.appendChild(img);
  document.body.appendChild(wrapper);

  await new Promise((resolve) => {
    img.onload = () => resolve(null);
    img.onerror = () => resolve(null);
  });

  const pngData = await elementToPngDataUrl(wrapper).catch(() => null);
  wrapper.remove();
  return pngData;
}

export async function exportProjectPDF(
  project: Project,
  renders: RoomRender[],
): Promise<void> {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  pdf.setFontSize(24);
  pdf.setTextColor(20, 20, 20);
  pdf.text(project.title || "Untitled Project", 14, 24);

  pdf.setFontSize(12);
  pdf.text(`Prompt: ${project.prompt || "N/A"}`, 14, 40, {
    maxWidth: pageWidth - 28,
  });
  pdf.text(`Style: ${project.style || "Not selected"}`, 14, 62);
  pdf.text(`Date generated: ${new Date().toLocaleString()}`, 14, 72);
  addFooter(pdf);

  pdf.addPage();
  pdf.setFontSize(18);
  pdf.setTextColor(20, 20, 20);
  pdf.text("2D Floor Plan", 14, 20);

  const floorPlanImage = await captureFloorPlan(project);
  if (floorPlanImage) {
    pdf.addImage(
      floorPlanImage,
      "PNG",
      14,
      28,
      pageWidth - 28,
      140,
      undefined,
      "FAST",
    );
  } else {
    pdf.setFontSize(12);
    pdf.text("No floor plan is available for this project.", 14, 36);
  }
  addFooter(pdf);

  for (const render of renders) {
    pdf.addPage();
    pdf.setFontSize(18);
    pdf.setTextColor(20, 20, 20);
    pdf.text(render.room_name || "Room Render", 14, 20);

    if (render.image_url) {
      const renderImage = await captureRenderImage(render.image_url);
      if (renderImage) {
        pdf.addImage(
          renderImage,
          "PNG",
          14,
          30,
          pageWidth - 28,
          150,
          undefined,
          "FAST",
        );
      } else {
        pdf.setFontSize(12);
        pdf.text("Unable to load render image for export.", 14, 32);
      }
    } else {
      pdf.setFontSize(12);
      pdf.text("No render image available.", 14, 32);
    }

    pdf.setFontSize(11);
    pdf.setTextColor(80, 80, 80);
    pdf.text(`Prompt: ${render.prompt_used || "N/A"}`, 14, pageHeight - 24, {
      maxWidth: pageWidth - 28,
    });
    addFooter(pdf);
  }

  pdf.save(`kairos-${safeFileName(project.title || "project")}.pdf`);
}
